services:
  gateway:
    build:
      context: ./gateway  
    ports:
      - "8000:8000"  
    networks:
      - app-network
    depends_on:
      - auth_service
      - inventory_service
      - riddle_service
      - game_service
      - lake_service

  auth_service:
    build:
      context: ./auth_service
    networks:
      - app-network  

  game_service:
    build:
      context: ./game_service
    networks:
      - app-network

  inventory_service:
    build:
      context: ./inventory_service
    networks:
      - app-network

  lake_service:
    build:
       context: ./lake_service 
    networks:
      - app-network     

  riddle_service:
    build:
      context: ./riddle_service
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge    

