
services:
  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - storage-service
      - inventory-service
      - riddle-service
      - location-service
    networks:
      - game-network

  storage-service:
    build: 
      context: ./storage_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - game-network

  inventory-service:
    build: 
      context: ./inventory_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - storage-service
    networks:
      - game-network

  riddle-service:
    build: 
      context: ./riddle_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - storage-service
    networks:
      - game-network

  location-service:
    build: 
      context: ./location_service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - storage-service
    networks:
      - game-network

networks:
  game-network:
    driver: bridge

